
# Data ingestion configuration
data_ingestion:
  source_URL: https://raw.githubusercontent.com/megokul/text-summarizer/main/input_data/summarizer-data.zip
  raw_data_filename: raw.zip
  dataset_name: samsum_dataset

data_transformation:
  tokenized_dataset_dir: tokenized_data

# Model trainer configuration
model_trainer:
  model_ckpt: google/pegasus-cnn_dailymail
  inference_model_filename: inference_model
  trained_model_filename: pegasus-samsum-model
  training_report_filename: training_report.yaml

model_evaluation:
  report_filename: evaluation_report.yaml

s3_handler:
  bucket_name: textsummarizer-dev-artifacts 

data_backup:
  s3_enabled: false
  local_enabled: true
